### ISSUE TITLE
VR Path Registry nore xyz is not an array

### ISSUE THREAD

**Issue by SamirAl-Skaf** [antilatency/Unity.AltTrackingOculusHmdSample#2]
When i try to run the second step (2.Launch) from this page https://antilatency.com/getting-started/latest/openvr#openvr 
in the windows command prompt i get this error message:

VR Path Registry node runtime is not an array
VR Path Registry node config is not an array
VR Path Registry node log is not an array

The line i was running in the windows command prompt was :
"C:/Program Files (x86)/Steam/steamapps/common/SteamVR/bin/win64/vrpathreg.exe" adddriver "C:/Users/sas/Desktop/OpenVRDriver/OpenVRDriver/antilatency"

My openvrpaths-file looks like this:

{
	"config" : 
	[
		"C:\\Program Files (x86)\\Steam\\config"
	],
	"external_drivers" : 
	[
		"C:\\Program Files (x86)\\Steam\\steamapps\\common\\MixedRealityVRDriver"
	],
	"jsonid" : "vrpathreg",
	"log" : 
	[
		"C:\\Program Files (x86)\\Steam\\logs"
	],
	"runtime" : 
	[
		"C:\\Program Files (x86)\\Steam\\steamapps\\common\\SteamVR"
	],
	"version" : 1
}

**Comment by ar-antilatency** [comment]
Pretty old issue, sorry for missing this, but I'll reply either way. Try a clean SteamVR reinstall and refer to our newest guide: [OpenVR driver](https://developers.antilatency.com/Software/OpenVR_Driver_en.html)
